/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ProjectProjectIdRecipeRecipeIdRouteImport } from './routes/project.$projectId.recipe.$recipeId'
import { Route as ProjectProjectIdEditRecipeIdRouteImport } from './routes/project.$projectId.edit.$recipeId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRecipeRecipeIdRoute =
  ProjectProjectIdRecipeRecipeIdRouteImport.update({
    id: '/recipe/$recipeId',
    path: '/recipe/$recipeId',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdEditRecipeIdRoute =
  ProjectProjectIdEditRecipeIdRouteImport.update({
    id: '/edit/$recipeId',
    path: '/edit/$recipeId',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/edit/$recipeId': typeof ProjectProjectIdEditRecipeIdRoute
  '/project/$projectId/recipe/$recipeId': typeof ProjectProjectIdRecipeRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/edit/$recipeId': typeof ProjectProjectIdEditRecipeIdRoute
  '/project/$projectId/recipe/$recipeId': typeof ProjectProjectIdRecipeRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/edit/$recipeId': typeof ProjectProjectIdEditRecipeIdRoute
  '/project/$projectId/recipe/$recipeId': typeof ProjectProjectIdRecipeRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/project/$projectId'
    | '/project/$projectId/edit/$recipeId'
    | '/project/$projectId/recipe/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/project/$projectId'
    | '/project/$projectId/edit/$recipeId'
    | '/project/$projectId/recipe/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/project/$projectId'
    | '/project/$projectId/edit/$recipeId'
    | '/project/$projectId/recipe/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/recipe/$recipeId': {
      id: '/project/$projectId/recipe/$recipeId'
      path: '/recipe/$recipeId'
      fullPath: '/project/$projectId/recipe/$recipeId'
      preLoaderRoute: typeof ProjectProjectIdRecipeRecipeIdRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/edit/$recipeId': {
      id: '/project/$projectId/edit/$recipeId'
      path: '/edit/$recipeId'
      fullPath: '/project/$projectId/edit/$recipeId'
      preLoaderRoute: typeof ProjectProjectIdEditRecipeIdRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdEditRecipeIdRoute: typeof ProjectProjectIdEditRecipeIdRoute
  ProjectProjectIdRecipeRecipeIdRoute: typeof ProjectProjectIdRecipeRecipeIdRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdEditRecipeIdRoute: ProjectProjectIdEditRecipeIdRoute,
  ProjectProjectIdRecipeRecipeIdRoute: ProjectProjectIdRecipeRecipeIdRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
