/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes.$recipeId'
import { Route as EditRecipeIdRouteImport } from './routes/edit.$recipeId'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRecipeIdRoute = EditRecipeIdRouteImport.update({
  id: '/edit/$recipeId',
  path: '/edit/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/edit/$recipeId': typeof EditRecipeIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/edit/$recipeId': typeof EditRecipeIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/edit/$recipeId': typeof EditRecipeIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new' | '/edit/$recipeId' | '/recipes/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/edit/$recipeId' | '/recipes/$recipeId'
  id: '__root__' | '/' | '/new' | '/edit/$recipeId' | '/recipes/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  EditRecipeIdRoute: typeof EditRecipeIdRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$recipeId': {
      id: '/edit/$recipeId'
      path: '/edit/$recipeId'
      fullPath: '/edit/$recipeId'
      preLoaderRoute: typeof EditRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  EditRecipeIdRoute: EditRecipeIdRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
